/**
 *
 * @authors Javier Molina, Carlos Solorzano, Luis Bolaños, Jarod Venegas and 
 * Aaron Campos.
 */
package dameo.GUI;

import dameo.GUI.BoardFrame;
import javax.swing.JOptionPane;

/**
 *
 * clase que hereda de JFrame para poder desplegar el menú de selección de
 * jugadores.
 */
public class SelectionMenu extends javax.swing.JFrame {

    /**
     * Constructor de clase
     */
    public SelectionMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        player2 = new javax.swing.JTextField();
        player1 = new javax.swing.JTextField();
        iconoRojas = new javax.swing.JLabel();
        iconoBlancas = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        preguntaColor = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        player2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        player2.setText("player2");
        player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ActionPerformed(evt);
            }
        });
        mainPanel.add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 90, 30));

        player1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        player1.setText("player1");
        player1.setToolTipText("");
        player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ActionPerformed(evt);
            }
        });
        mainPanel.add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 30));

        iconoRojas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dameoGUI/images/red.png"))); // NOI18N
        mainPanel.add(iconoRojas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        iconoBlancas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dameoGUI/images/white.png"))); // NOI18N
        mainPanel.add(iconoBlancas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        playButton.setBackground(new java.awt.Color(102, 102, 0));
        playButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        playButton.setForeground(java.awt.SystemColor.info);
        playButton.setText("Jugar");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        mainPanel.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 120, 50));

        preguntaColor.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        preguntaColor.setForeground(new java.awt.Color(51, 51, 0));
        preguntaColor.setText("¿Quienes Juegan?");
        preguntaColor.setToolTipText("");
        mainPanel.add(preguntaColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dameoGUI/images/board.png"))); // NOI18N
        mainPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método encargado de manejar los eventos del objeto playButton Se revisa que
     * los campos para escribir los nombres de jugadores no estén vacíos, si ambos
     * campos tienen datos entonces se crea un objeto BoardFrame; se cierra la
     * ventana actual y se hace visible la ventana del BoardBrame donde el juego se
     * ejecuta.
     * 
     * @param evt evento a manejar
     */
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_playButtonActionPerformed
        // TODO add your handling code here:
        if (!this.player1.getText().equals("") && !this.player2.getText().equals("")) {
            BoardFrame gui = new BoardFrame(this.player1.getText(), this.player2.getText());
            this.setVisible(false);
            gui.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de los dos jugadores");
        }
    }// GEN-LAST:event_playButtonActionPerformed

    private void player2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_player2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_player2ActionPerformed

    private void player1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_player1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_player1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel iconoBlancas;
    private javax.swing.JLabel iconoRojas;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton playButton;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JLabel preguntaColor;
    // End of variables declaration//GEN-END:variables
}
